/*INSERT INTO TB_PESSOA (ID, NM_PESSOA, DT_NASCI) VALUES (1, 'Gabriel Figueiredo Fernandes Lobão', '2000-05-24');
INSERT INTO TB_PESSOA (ID, NM_PESSOA, DT_NASCI) VALUES (2, 'Fernanda Silva', '1995-10-15');
INSERT INTO TB_PESSOA (ID, NM_PESSOA, DT_NASCI) VALUES (3, 'Rafael Almeida', '1988-03-07');
INSERT INTO TB_PESSOA (ID, NM_PESSOA, DT_NASCI) VALUES (4, 'Mariana Santos', '1990-07-22');
INSERT INTO TB_PESSOA (ID, NM_PESSOA, DT_NASCI)VALUES (5, 'Rodrigo Oliveira', '1985-12-18');
INSERT INTO TB_PESSOA (ID, NM_PESSOA, DT_NASCI) VALUES (6, 'Camila Costa', '1998-09-30');
INSERT INTO TB_PESSOA (ID, NM_PESSOA, DT_NASCI) VALUES (7, 'Lucas Martins', '1993-04-12');
INSERT INTO TB_PESSOA (ID, NM_PESSOA, DT_NASCI) VALUES (8, 'Isabela Pereira', '1987-08-08');
INSERT INTO TB_PESSOA (ID, NM_PESSOA, DT_NASCI) VALUES (9, 'Diego Sousa', '1992-01-28');
INSERT INTO TB_PESSOA (ID, NM_PESSOA, DT_NASCI) VALUES (10, 'Carolina Lima', '2001-06-05');
INSERT INTO TB_PESSOA (ID, NM_PESSOA, DT_NASCI) VALUES (11, 'Felipe Oliveira', '1997-11-20');
INSERT INTO TB_PESSOA (ID, NM_PESSOA, DT_NASCI) VALUES (12, 'Ana Clara Fernandes', '1989-02-14');
INSERT INTO TB_PESSOA (ID, NM_PESSOA, DT_NASCI) VALUES (13, 'Pedro Santos', '1994-05-17');
INSERT INTO TB_PESSOA (ID, NM_PESSOA, DT_NASCI) VALUES (14, 'Juliana Souza', '1986-10-09');
INSERT INTO TB_PESSOA (ID, NM_PESSOA, DT_NASCI) VALUES (15, 'Marcos Lima', '1991-03-23');
INSERT INTO TB_PESSOA (ID, NM_PESSOA, DT_NASCI) VALUES (16, 'Amanda Vieira', '1996-07-10');
INSERT INTO TB_PESSOA (ID, NM_PESSOA, DT_NASCI) VALUES (17, 'Gustavo Oliveira', '1984-12-04');
INSERT INTO TB_PESSOA (ID, NM_PESSOA, DT_NASCI) VALUES (18, 'Renata Costa', '1999-09-14');
INSERT INTO TB_PESSOA (ID, NM_PESSOA, DT_NASCI) VALUES (19, 'Bruno Silva', '1983-06-30');
INSERT INTO TB_PESSOA (ID, NM_PESSOA, DT_NASCI) VALUES (20, 'Larissa Rodrigues', '1990-11-27');



INSERT INTO TB_ENDERECO (ESTADO, NUMERO, ID, PESSOA_ID, CEP, CIDADE, LOGRADOURO, TP_PRINCIPAL) VALUES (0, 302, 1, 1, '29175225', 'RIO DE JANEIRO', 'RUA MANUEL BASTOS DE OLIVEIRA', 'N');
INSERT INTO TB_ENDERECO (ESTADO, NUMERO, ID, PESSOA_ID, CEP, CIDADE, LOGRADOURO, TP_PRINCIPAL) VALUES (1, 402, 2, 2, '29180225', 'SÃO PAULO', 'AVENIDA PAULISTA', 'S');
INSERT INTO TB_ENDERECO (ESTADO, NUMERO, ID, PESSOA_ID, CEP, CIDADE, LOGRADOURO, TP_PRINCIPAL) VALUES (2, 502, 3, 1, '29145225', 'BELO HORIZONTE', 'RUA AUGUSTO DE LIMA', 'N');
INSERT INTO TB_ENDERECO (ESTADO, NUMERO, ID, PESSOA_ID, CEP, CIDADE, LOGRADOURO, TP_PRINCIPAL) VALUES (3, 602, 4, 3, '29185225', 'BRASÍLIA', 'ESPLANADA DOS MINISTÉRIOS', 'S');
INSERT INTO TB_ENDERECO (ESTADO, NUMERO, ID, PESSOA_ID, CEP, CIDADE, LOGRADOURO, TP_PRINCIPAL) VALUES (4, 702, 5, 2, '29125225', 'RECIFE', 'AVENIDA BOA VIAGEM', 'N');
INSERT INTO TB_ENDERECO (ESTADO, NUMERO, ID, PESSOA_ID, CEP, CIDADE, LOGRADOURO, TP_PRINCIPAL) VALUES (5, 802, 6, 1, '29185225', 'FLORIANÓPOLIS', 'RUA MAJOR ÁVILA', 'N');
INSERT INTO TB_ENDERECO (ESTADO, NUMERO, ID, PESSOA_ID, CEP, CIDADE, LOGRADOURO, TP_PRINCIPAL) VALUES (6, 902, 7, 3, '29135225', 'PORTO ALEGRE', 'AVENIDA BORGES DE MEDEIROS', 'N');
INSERT INTO TB_ENDERECO (ESTADO, NUMERO, ID, PESSOA_ID, CEP, CIDADE, LOGRADOURO, TP_PRINCIPAL) VALUES (7, 1002, 8, 2, '29155225', 'SALVADOR', 'RUA DIREITA DE SÃO PEDRO', 'S');
INSERT INTO TB_ENDERECO (ESTADO, NUMERO, ID, PESSOA_ID, CEP, CIDADE, LOGRADOURO, TP_PRINCIPAL) VALUES (8, 1102, 9, 1, '29165225', 'CURITIBA', 'AVENIDA SETE DE SETEMBRO', 'N');
INSERT INTO TB_ENDERECO (ESTADO, NUMERO, ID, PESSOA_ID, CEP, CIDADE, LOGRADOURO, TP_PRINCIPAL) VALUES (9, 1202, 10, 3, '29175225', 'MANAUS', 'RUA MAJOR GABRIEL', 'N');
INSERT INTO TB_ENDERECO (ESTADO, NUMERO, ID, PESSOA_ID, CEP, CIDADE, LOGRADOURO, TP_PRINCIPAL) VALUES (10, 1302, 11, 1, '29145225', 'FORTALEZA', 'AVENIDA BEIRA MAR', 'N');
INSERT INTO TB_ENDERECO (ESTADO, NUMERO, ID, PESSOA_ID, CEP, CIDADE, LOGRADOURO, TP_PRINCIPAL) VALUES (11, 1402, 12, 2, '29175225', 'GOIÂNIA', 'RUA 82', 'N');
INSERT INTO TB_ENDERECO (ESTADO, NUMERO, ID, PESSOA_ID, CEP, CIDADE, LOGRADOURO, TP_PRINCIPAL) VALUES (12, 1502, 13, 3, '29195225', 'NATAL', 'RUA DOS CAICÓS', 'N');
INSERT INTO TB_ENDERECO (ESTADO, NUMERO, ID, PESSOA_ID, CEP, CIDADE, LOGRADOURO, TP_PRINCIPAL) VALUES (13, 1602, 14, 2, '29125225', 'JOÃO PESSOA', 'AVENIDA EPITÁCIO PESSOA', 'N');
INSERT INTO TB_ENDERECO (ESTADO, NUMERO, ID, PESSOA_ID, CEP, CIDADE, LOGRADOURO, TP_PRINCIPAL) VALUES (14, 1702, 15, 1, '29155225', 'TERESINA', 'RUA DOUTOR ÁREA LEÃO', 'N');
INSERT INTO TB_ENDERECO (ESTADO, NUMERO, ID, PESSOA_ID, CEP, CIDADE, LOGRADOURO, TP_PRINCIPAL) VALUES (15, 1802, 16, 3, '29185225', 'VITÓRIA', 'RUA DOMINGOS MARTINS', 'S');
INSERT INTO TB_ENDERECO (ESTADO, NUMERO, ID, PESSOA_ID, CEP, CIDADE, LOGRADOURO, TP_PRINCIPAL) VALUES (16, 1902, 17, 2, '29115225', 'CUIABÁ', 'AVENIDA HISTORIADOR RUBENS DE MENDONÇA', 'N');
INSERT INTO TB_ENDERECO (ESTADO, NUMERO, ID, PESSOA_ID, CEP, CIDADE, LOGRADOURO, TP_PRINCIPAL) VALUES (17, 2002, 18, 1, '29135225', 'PALMAS', 'AVENIDA TEOTÔNIO SEGUROS', 'S');
INSERT INTO TB_ENDERECO (ESTADO, NUMERO, ID, PESSOA_ID, CEP, CIDADE, LOGRADOURO, TP_PRINCIPAL) VALUES (18, 2102, 19, 3, '29155225', 'CAMPO GRANDE', 'AVENIDA AFONSO PENA', 'N');

*/